//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutenticacionPersonalizada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public System.Guid Id { get; set; }
        public string titulo { get; set; }
        public System.DateTime inicio { get; set; }
        public System.Guid IdTipoCita { get; set; }
        public string estatus { get; set; }
    
        public virtual TiposCitas TiposCitas { get; set; }
    }
}
